export const UPDATE_FIELD = 'UPDATE_FIELD';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_TEMPLATES = 'UPDATE_TEMPLATES';
export const DELETE_TEMPLATES = 'DELETE_TEMPLATES';
export const ADD_TEMPLATE = 'ADD_TEMPLATE';
export const UPDATE_DISPLAYED_TEMPLATE = 'UPDATE_DISPLAYED_TEMPLATE';
export const ADD_RECIPIENT = 'ADD_RECIPIENT';
export const UPDATE_RESPONSE = 'UPDATE_RESPONSE';
