export const UPDATE_FIELD = 'UPDATE_FIELD';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_TEMPLATES = 'UPDATE_TEMPLATES';
export const UPDATE_DISPLAYED_TEMPLATE = 'UPDATE_DISPLAYED_TEMPLATE';
